# This is the development branch

There are many features that will be added slowly and be merged with master as time goes on. The expected features are
 1. S4 classes and metaclasses for data and easy construction function. 
 2. Posterior probablility integration to be used with RSEM
 3. SQLite backend for even lower memory footprint. 
 
 I will update the master branch as these features become available. 
 
 I will also be doing some testing on some of the other functions and will update any changes in the master branch. 


TODO

S4 classes for ribo objects, 

  different sections for ribo and RNA, use the existing functions for getting the data. 
  
  Meta experiment class that contains the ribo objects along with sequence and experimental information. 
  
  Wrappers to creaste a BSGenome and TxDb from custom fasta and GTF/GFF
  
  Function to add custom arbitrary slots to the meta class. 
  
  Find a way to use posterior probabilties to be used in read_profiling_data()
  
  This is probably another branch as it requries a few re-writes
    
    functions to be called from the command line after alingment to add everything to an SQLite databse - this should probably be python
  
    functions to query this database basically a re-write of the existing functions. 
  
